import Foundation
import GRDB

public struct Cluster: Identifiable, Codable, Equatable, Sendable {
    public var id: UUID
    public var name: String
    public var taskIds: [UUID]   // stored as JSON
    public var quadrant: Quadrant
    public var isAutoGenerated: Bool
    public var createdAt: Date
    public var updatedAt: Date

    public init(
        id: UUID = UUID(),
        name: String,
        taskIds: [UUID] = [],
        quadrant: Quadrant,
        isAutoGenerated: Bool = false,
        createdAt: Date = Date(),
        updatedAt: Date = Date()
    ) {
        self.id = id
        self.name = name
        self.taskIds = taskIds
        self.quadrant = quadrant
        self.isAutoGenerated = isAutoGenerated
        self.createdAt = createdAt
        self.updatedAt = updatedAt
    }
}

extension Cluster: FetchableRecord, PersistableRecord, MutablePersistableRecord {
    public static let databaseTableName = "clusters"

    public func encode(to container: inout PersistenceContainer) throws {
        container["id"]              = id.uuidString
        container["name"]            = name
        container["taskIdsJSON"]     = try String(data: JSONEncoder().encode(taskIds.map(\.uuidString)), encoding: .utf8)
        container["quadrant"]        = quadrant.rawValue
        container["isAutoGenerated"] = isAutoGenerated
        container["createdAt"]       = createdAt
        container["updatedAt"]       = updatedAt
    }

    public init(row: Row) throws {
        id             = UUID(uuidString: row["id"] as String) ?? UUID()
        name           = row["name"]
        taskIds        = ((try? JSONDecoder().decode([String].self, from: Data((row["taskIdsJSON"] as String? ?? "[]").utf8))) ?? [])
                            .compactMap(UUID.init)
        quadrant       = Quadrant(rawValue: row["quadrant"] as Int) ?? .eliminate
        isAutoGenerated = row["isAutoGenerated"]
        createdAt      = row["createdAt"]
        updatedAt      = row["updatedAt"]
    }
}
