import Foundation
import GRDB

/// Database migrations. Add new migrations at the end — never modify existing ones.
enum Migrations {

    static func register(in migrator: inout DatabaseMigrator) {
        // v1: Initial schema
        migrator.registerMigration("v1_initial") { db in
            try db.create(table: "tasks") { t in
                t.column("id",               .text).notNull().primaryKey()
                t.column("title",            .text).notNull()
                t.column("quadrant",         .integer).notNull()
                t.column("dueDate",          .datetime)
                t.column("createdAt",        .datetime).notNull()
                t.column("updatedAt",        .datetime).notNull()
                t.column("completedAt",      .datetime)
                t.column("isArchived",       .boolean).notNull().defaults(to: false)
                t.column("tagsJSON",         .text).notNull().defaults(to: "[]")
                t.column("clusterId",        .text)
                t.column("source",           .text).notNull().defaults(to: "manual")
                t.column("parsedUrgency",    .double)
                t.column("parsedImportance", .double)
            }

            // Index for the most common query: active tasks per quadrant, sorted by creation date
            try db.create(
                indexOn: "tasks",
                columns: ["quadrant", "isArchived", "createdAt"]
            )

            // Index for CloudKit sync: fetch tasks modified after a given date
            try db.create(
                indexOn: "tasks",
                columns: ["updatedAt"]
            )

            try db.create(table: "clusters") { t in
                t.column("id",              .text).notNull().primaryKey()
                t.column("name",            .text).notNull()
                t.column("taskIdsJSON",     .text).notNull().defaults(to: "[]")
                t.column("quadrant",        .integer).notNull()
                t.column("isAutoGenerated", .boolean).notNull().defaults(to: false)
                t.column("createdAt",       .datetime).notNull()
                t.column("updatedAt",       .datetime).notNull()
            }

            // Schema version tracking table (used by DatabaseMigrator internally,
            // but also useful for manual introspection and backup tooling)
            try db.create(table: "schema_meta", ifNotExists: true) { t in
                t.column("key",   .text).notNull().primaryKey()
                t.column("value", .text).notNull()
            }
            try db.execute(
                sql: "INSERT INTO schema_meta (key, value) VALUES (?, ?)",
                arguments: ["created_at", ISO8601DateFormatter().string(from: Date())]
            )
        }

        // v2: Replace clusterId (foreign key) with clusterName (plain string), add userNotes
        migrator.registerMigration("v2_cluster_name") { db in
            try db.alter(table: "tasks") { t in
                t.add(column: "clusterName", .text)
                t.add(column: "userNotes",   .text)
            }
        }

        // v3: 1:1 Contact Manager — contacts + sessions
        migrator.registerMigration("v3_contacts") { db in
            try db.create(table: "contacts") { t in
                t.column("id",              .text).notNull().primaryKey()
                t.column("name",            .text).notNull()
                t.column("role",            .text)
                t.column("area",            .text)
                t.column("cadenceDays",     .integer).notNull().defaults(to: 14)
                t.column("lastMeetingDate", .datetime)
                t.column("notes",           .text).notNull().defaults(to: "")
                t.column("reminderTaskId",  .text)
                t.column("createdAt",       .datetime).notNull()
                t.column("updatedAt",       .datetime).notNull()
            }

            try db.create(table: "sessions") { t in
                t.column("id",        .text).notNull().primaryKey()
                t.column("contactId", .text).notNull()
                    .references("contacts", onDelete: .cascade)
                t.column("date",      .datetime).notNull()
                t.column("notes",     .text).notNull().defaults(to: "")
                t.column("createdAt", .datetime).notNull()
            }

            try db.create(indexOn: "sessions", columns: ["contactId"])
        }

        // v4: Keyboard-first navigation — manual task ordering within quadrants.
        // Positions are keyed by task UUID string. When tasks are loaded from EventKit
        // they are sorted by position ascending; new tasks append at the end.
        migrator.registerMigration("v4_task_positions") { db in
            try db.create(table: "task_positions") { t in
                t.column("id",       .text).notNull().primaryKey()  // Task UUID string
                t.column("quadrant", .integer).notNull()
                t.column("position", .integer).notNull()
            }
        }
    }
}
