export type Quadrant = 1 | 2 | 3 | 4;

export interface Task {
  id: string;
  title: string;
  quadrant: Quadrant;
  dueDate: string | null; // ISO string for serialization
  createdAt: string;
  completedAt: string | null;
  isArchived: boolean;
  tags: string[];
  clusterId: string | null;
  metadata: {
    source: 'manual' | 'parsed';
    parsedUrgency?: number;
    parsedImportance?: number;
  };
}

export interface Cluster {
  id: string;
  name: string;
  taskIds: string[];
  quadrant: Quadrant;
  isAutoGenerated: boolean;
  createdAt: string;
}

export type UrgencyLevel = 'overdue' | 'critical' | 'warning' | 'soon' | 'normal';

export type ViewMode = 'matrix' | 'archive';

export interface FilterState {
  search: string;
  quadrants: Quadrant[];
  tags: string[];
  showCompleted: boolean;
}

export const QUADRANT_CONFIG: Record<Quadrant, {
  label: string;
  subtitle: string;
  color: string;
  headerBg: string;
  borderColor: string;
}> = {
  1: {
    label: 'Urgent & Important',
    subtitle: 'Do First',
    color: 'text-red-700 dark:text-red-400',
    headerBg: 'bg-red-50 dark:bg-red-950/40',
    borderColor: 'border-red-200 dark:border-red-800',
  },
  2: {
    label: 'Not Urgent & Important',
    subtitle: 'Schedule',
    color: 'text-blue-700 dark:text-blue-400',
    headerBg: 'bg-blue-50 dark:bg-blue-950/40',
    borderColor: 'border-blue-200 dark:border-blue-800',
  },
  3: {
    label: 'Urgent & Not Important',
    subtitle: 'Delegate',
    color: 'text-amber-700 dark:text-amber-400',
    headerBg: 'bg-amber-50 dark:bg-amber-950/40',
    borderColor: 'border-amber-200 dark:border-amber-800',
  },
  4: {
    label: 'Not Urgent & Not Important',
    subtitle: 'Eliminate',
    color: 'text-gray-600 dark:text-gray-400',
    headerBg: 'bg-gray-50 dark:bg-gray-800/60',
    borderColor: 'border-gray-200 dark:border-gray-700',
  },
};
